### ISSUE TITLE
Why make backward-incompatible changes?!

### ISSUE THREAD

**Issue by spoganshev** [yandex-money-tech/grafana-dashboard-dsl#1]
There are a lot of backward-incompatible changes in the last couple of weeks?

Like this https://github.com/yandex-money-tech/grafana-dashboard-dsl/commit/5c986cf2c757e608a3093411b2dc13ad66c102c4

Also, some features have been removed (like in SingleStatPanel).

Just one question: Why?!

**Comment by f0y** [comment]
The truth is we don't think that someone uses the library. From now we will pay more attention to backward compatibility.
All changes are logged in [CHANGELOG.md](https://github.com/yandex-money-tech/grafana-dashboard-dsl/blob/master/CHANGELOG.md), so you can look there for new features or migration instruction to major versions.

We will develop a massive amount of new features in several next months, so I think backward-incompatible changes are inevitable.
